// src/router-config.js
// React Router에서 사용하는 라우팅 상수/매핑
// 모든 페이지가 src/pages/*.jsx 로 변환 완료 — loader 값은 null (AppLayout의 REACT_PAGES가 항상 우선)

export const LAST_PAGE_KEY = 'invex_last_page_v1';

// PAGE_LOADERS: 페이지 ID 목록 (route 등록용). 값은 사용되지 않음.
export const PAGE_LOADERS = {
  home: null, upload: null, mapping: null,
  inventory: null, in: null, out: null,
  summary: null, scanner: null, documents: null,
  dashboard: null, transfer: null, ledger: null,
  settings: null, vendors: null, stocktake: null,
  bulk: null, costing: null, labels: null,
  accounts: null, warehouses: null, roles: null,
  api: null, billing: null, admin: null,
  mypage: null, guide: null, support: null,
  team: null, 'tax-reports': null, profit: null,
  backup: null, orders: null, forecast: null,
  referral: null, sales: null, 'weekly-report': null,
  pos: null, 'hr-dashboard': null, employees: null,
  attendance: null, payroll: null, leaves: null,
  severance: null, 'yearend-settlement': null,
  auditlog: null, 'org-chart': null,
  'hub-inventory': null, 'hub-warehouse': null,
  'hub-order': null, 'hub-report': null,
  'hub-documents': null, 'hub-settings': null,
  'hub-support': null, 'hub-hr': null,
};

// 페이지 라벨 (브레드크럼용)
export const PAGE_LABELS = {
  home: '대시보드',
  inventory: '재고현황',
  in: '입고관리',
  out: '출고관리',
  ledger: '수불관리',
  upload: '파일 업로드',
  mapping: '컬럼 매핑',
  summary: '요약 보고',
  profit: '손익 분석',
  costing: '원가 분석',
  dashboard: '고급 분석',
  accounts: '매출·매입',
  scanner: '바코드 스캐너',
  documents: '문서 생성',
  orders: '발주 관리',
  forecast: '수요 예측',
  vendors: '거래처 관리',
  warehouses: '다중 창고 관리',
  transfer: '창고 이동',
  stocktake: '재고 실사',
  bulk: '일괄 처리',
  labels: '라벨 출력',
  settings: '기본 설정',
  team: '팀 관리',
  roles: '권한 관리',
  api: 'API 연동',
  billing: '구독 관리',
  backup: '백업·복원',
  mypage: '마이페이지',
  guide: '사용 가이드',
  support: '고객 문의',
  referral: '추천 프로그램',
  'weekly-report': '주간 보고서',
  'tax-reports': '세무·회계 서류',
  pos: 'POS 매출분석',
  admin: '관리자',
  auditlog: '감사 추적',
  'org-chart': '조직도',
  'hr-dashboard': 'HR 대시보드',
  employees: '직원 관리',
  attendance: '근태 관리',
  payroll: '급여 계산',
  leaves: '휴가·연차',
  severance: '퇴직금 계산',
  'yearend-settlement': '연말정산',
  sales: '수주 관리',
};
